done

diff --git a/0x04-loops_conditions_and_parsing/100-read_and_cut b/0x04-loops_conditions_and_parsing/100-read_and_cut
--- a/0x04-loops_conditions_and_parsing/100-read_and_cut
+++ b/0x04-loops_conditions_and_parsing/100-read_and_cut
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
-# displays username, user id and home directory for each line of /etc/passwd.
+# read file
+file="/etc/passwd"
 
-input="/etc/passwd"
-while IFS= read -r line
-do
-    echo "$line" | cut -d':' --fields=1,3,6
-done < "$input"
+if [ ! -r "$file" ]; then
+    echo "Error: File $file not found or not readable."
+    exit 1
+fi
+
+while IFS=":" read -r username _ uid _ home _; do
+    echo "$username:$uid:$home"
+done < "$file"
+
diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,29 @@
 #!/usr/bin/env bash
-# Transfers a file from Holberton's client to another.
-# Accepts four arguments:
-#+    The path to the file to be transferred.
-#+    The IP of the server to transfer the file to.
-#+    The username that scp connects with.
-#+    The path to the SSH private key that scp uses.
+# transfers a file to a remote server
 
-if [ $# -lt 4 ]
-then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+if [ "$#" -ne 4 ]; then
+	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
+fi
+
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key_path="$4"
+
+if [ ! -f "$file_path" ]; then
+	echo "Error: The specified file does not exist."
+	exit 1
+fi
+
+#lets dissable host key checking for scp
+
+scp_options=(-o StrictHostKeyChecking=no -i "$ssh_key_path")
+
+echo "Transferring file to $username@$server_ip:~/"
+
+if scp "${scp_options[@]}" "$file_path" "$username@$server_ip:~/"; then
+	echo "File transfer successful."
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+	echo "Error: File transfer failed."
 fi
